services:
  db:
    image: postgres:15
    container_name: postgres_wallets
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallets_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_wallets
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/wallets_db
    ports:
      - "8000:8000"
    volumes:
      - ./alembic/versions:/app/alembic/versions

volumes:
  pg_data: